# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

deploy-azure:
  needs: build
  name: Deploy-Azure
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'
  environment:
    name: AZURE-PRO
    url: https://devopsfiap-on-app.azurewebsites.net/
  steps:
    - name: Download JAR
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: target/

    - name: DeployAzure
      uses: azure/webapps-deploy@v2
      with:
        app-name: devopsfiap-on-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/target/*.jar